/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.gui;

import com.mycompany.moviemanagementsystem.Constants;
import com.mycompany.moviemanagementsystem.Movie;
import com.mycompany.moviemanagementsystem.MovieFactor;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JFrame;

/**
 *
 * @author Vasilis
 */
public class DetailsMovieFrame extends javax.swing.JFrame implements WindowListener{

    /**
     * Creates new form DetailsMovieFrame
     */    
    private JButton detailsMovieButton;
    private ArrayList<JButton> buttonList;
    
    public DetailsMovieFrame(Movie movie, ArrayList<JButton> buttonList) {
        initComponents();      
        addListener();
        addWindowListener(this);
        showMovieDetails(movie);
        
        this.buttonList = buttonList;
             
        setMainPanelMovieButtons(false);
        
        this.setVisible(true);
        this.setTitle(Constants.MOVIE_DETAILS_FRAME_TITLE);
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }
    
    private void addListener(){
        closeButton.addActionListener(new ButtonListener());
    }
    
    private void setDetailsMovieButton(boolean enabled){
        this.detailsMovieButton.setEnabled(enabled);
    }
    
    
    private void setMainPanelMovieButtons(boolean enabled){
        for(JButton button : buttonList){
            button.setEnabled(enabled);
        }
    }
    
    private void showMovieDetails(Movie movie){
        movieCodeField.setText(movie.getCode());
        movieTitleField.setText(movie.getTitle());
        movieTypeField.setText(movie.getType());
        movieYearField.setText(String.valueOf(movie.getYear()));
        moviePlotArea.setText(movie.getPlot());
        for(MovieFactor actor : movie.getActors()){
           movieActorsArea.append(actor + "\n");
        }
        MovieFactor director = movie.getDirector();
        movieDirectorFirstNameField.setText(director.getFirstName());
        movieDirectorLastNameField.setText(director.getLastName());
        moviePlaytimeField.setText(String.valueOf(movie.getPlayTime()));
        
        NumberFormat priceFormat = new DecimalFormat("#0.00");
        moviePriceField.setText(String.valueOf(priceFormat.format(movie.getPrice())));
        movieQuantityField.setText(String.valueOf(movie.getQuantity()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        moviePanel = new javax.swing.JPanel();
        movieCodeLabel = new javax.swing.JLabel();
        movieCodeField = new javax.swing.JTextField();
        movieTitleLabel = new javax.swing.JLabel();
        movieTitleField = new javax.swing.JTextField();
        movieYearLabel = new javax.swing.JLabel();
        movieYearField = new javax.swing.JTextField();
        moviePlotLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        moviePlotArea = new javax.swing.JTextArea();
        movieActorsLabel = new javax.swing.JLabel();
        movieDirector = new javax.swing.JLabel();
        movieDirectorFirstNameField = new javax.swing.JTextField();
        moviePlaytimeLabel = new javax.swing.JLabel();
        moviePlaytimeField = new javax.swing.JTextField();
        moviePriceLabel = new javax.swing.JLabel();
        moviePriceField = new javax.swing.JTextField();
        movieQuantityLabel = new javax.swing.JLabel();
        movieQuantityField = new javax.swing.JTextField();
        closeButton = new javax.swing.JButton();
        movieDirectorLastNameField = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        movieActorsArea = new javax.swing.JTextArea();
        movieTypeLabel = new javax.swing.JLabel();
        movieTypeField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        movieCodeLabel.setText("Code: ");

        movieCodeField.setEditable(false);

        movieTitleLabel.setText("Title:");

        movieTitleField.setEditable(false);

        movieYearLabel.setText("Year:");

        movieYearField.setEditable(false);

        moviePlotLabel.setText("Plot:");

        moviePlotArea.setEditable(false);
        moviePlotArea.setColumns(20);
        moviePlotArea.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        moviePlotArea.setRows(5);
        jScrollPane1.setViewportView(moviePlotArea);

        movieActorsLabel.setText("Actors:");

        movieDirector.setText("Director: ");

        movieDirectorFirstNameField.setEditable(false);

        moviePlaytimeLabel.setText("Playtime (secs):");

        moviePlaytimeField.setEditable(false);

        moviePriceLabel.setText("Price:");

        moviePriceField.setEditable(false);

        movieQuantityLabel.setText("Quantity:");

        movieQuantityField.setEditable(false);

        closeButton.setText("Close");

        movieDirectorLastNameField.setEditable(false);

        movieActorsArea.setColumns(20);
        movieActorsArea.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        movieActorsArea.setRows(5);
        jScrollPane3.setViewportView(movieActorsArea);

        movieTypeLabel.setText("Type:");

        movieTypeField.setEditable(false);

        javax.swing.GroupLayout moviePanelLayout = new javax.swing.GroupLayout(moviePanel);
        moviePanel.setLayout(moviePanelLayout);
        moviePanelLayout.setHorizontalGroup(
            moviePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(moviePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(moviePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(moviePanelLayout.createSequentialGroup()
                        .addGroup(moviePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(moviePlotLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(movieTitleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(movieCodeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(moviePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(moviePanelLayout.createSequentialGroup()
                                .addGroup(moviePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(movieCodeField)
                                    .addComponent(movieTitleField, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addComponent(movieTypeLabel)
                                .addGap(18, 18, 18)
                                .addComponent(movieTypeField)
                                .addGap(18, 18, 18)
                                .addComponent(movieYearLabel)
                                .addGap(18, 18, 18)
                                .addComponent(movieYearField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(moviePanelLayout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(moviePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, moviePanelLayout.createSequentialGroup()
                            .addComponent(moviePlaytimeLabel)
                            .addGap(18, 18, 18)
                            .addComponent(moviePlaytimeField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(moviePriceLabel)
                            .addGap(18, 18, 18)
                            .addComponent(moviePriceField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(movieQuantityLabel)
                            .addGap(18, 18, 18)
                            .addComponent(movieQuantityField))
                        .addGroup(moviePanelLayout.createSequentialGroup()
                            .addComponent(movieDirector)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(movieDirectorFirstNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(movieDirectorLastNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, moviePanelLayout.createSequentialGroup()
                            .addComponent(movieActorsLabel)
                            .addGap(18, 18, 18)
                            .addComponent(jScrollPane3)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, moviePanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(closeButton)))
                .addContainerGap())
        );
        moviePanelLayout.setVerticalGroup(
            moviePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(moviePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(moviePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(movieCodeLabel)
                    .addComponent(movieCodeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(moviePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(movieTitleLabel)
                    .addComponent(movieTitleField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(movieYearLabel)
                    .addComponent(movieYearField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(movieTypeLabel)
                    .addComponent(movieTypeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(moviePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(moviePlotLabel)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(moviePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(movieActorsLabel)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(moviePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(movieDirector)
                    .addComponent(movieDirectorFirstNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(movieDirectorLastNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(moviePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(moviePlaytimeLabel)
                    .addComponent(moviePlaytimeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(moviePriceLabel)
                    .addComponent(moviePriceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(movieQuantityLabel)
                    .addComponent(movieQuantityField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(closeButton)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(moviePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(moviePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DetailsMovieFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DetailsMovieFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DetailsMovieFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DetailsMovieFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new DetailsMovieFrame().setVisible(true);
//            }
//        });
    }

    @Override
    public void windowOpened(WindowEvent e) {}

    @Override
    public void windowClosing(WindowEvent e) {
        setMainPanelMovieButtons(true);
    }

    @Override
    public void windowClosed(WindowEvent e) {}

    @Override
    public void windowIconified(WindowEvent e) {}

    @Override
    public void windowDeiconified(WindowEvent e) {}

    @Override
    public void windowActivated(WindowEvent e) {}

    @Override
    public void windowDeactivated(WindowEvent e) {}
    
    class ButtonListener implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent event) {
           if(event.getSource() == closeButton){
               setMainPanelMovieButtons(true);
               dispose();
           }
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea movieActorsArea;
    private javax.swing.JLabel movieActorsLabel;
    private javax.swing.JTextField movieCodeField;
    private javax.swing.JLabel movieCodeLabel;
    private javax.swing.JLabel movieDirector;
    private javax.swing.JTextField movieDirectorFirstNameField;
    private javax.swing.JTextField movieDirectorLastNameField;
    private javax.swing.JPanel moviePanel;
    private javax.swing.JTextField moviePlaytimeField;
    private javax.swing.JLabel moviePlaytimeLabel;
    private javax.swing.JTextArea moviePlotArea;
    private javax.swing.JLabel moviePlotLabel;
    private javax.swing.JTextField moviePriceField;
    private javax.swing.JLabel moviePriceLabel;
    private javax.swing.JTextField movieQuantityField;
    private javax.swing.JLabel movieQuantityLabel;
    private javax.swing.JTextField movieTitleField;
    private javax.swing.JLabel movieTitleLabel;
    private javax.swing.JTextField movieTypeField;
    private javax.swing.JLabel movieTypeLabel;
    private javax.swing.JTextField movieYearField;
    private javax.swing.JLabel movieYearLabel;
    // End of variables declaration//GEN-END:variables
}
