/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.gui;

import com.mycompany.moviemanagementsystem.Constants;
import com.mycompany.moviemanagementsystem.Movie;
import com.mycompany.moviemanagementsystem.MovieFactor;
import com.mycompany.moviemanagementsystem.Status;
import database.MovieHandler;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.WindowConstants;
import validators.MovieValidator;

/**
 *
 * @author Vasilis
 */
public class EditMovieFrame extends javax.swing.JFrame implements WindowListener{

    /**
     * Creates new form EditMovieFrame
     */
    private MoviePanel.MovieTableModel movieTableModel;
    private ArrayList<Movie> movies;
    private int index;
    private DefaultListModel listModel;
    private ArrayList<JButton> buttonList;
    private MovieValidator validator;
    private MovieHandler movieHandler;
    
    public EditMovieFrame(int index, ArrayList<Movie> movies, MoviePanel.MovieTableModel movieTableModel, ArrayList<JButton> buttonList, MovieHandler movieHandler) {
        initComponents();
        initComboBox();
        bindListenerToButtons();
        addWindowListener(this);
        
        this.index = index;
        this.movies = movies;
        this.movieTableModel = movieTableModel;
        this.buttonList = buttonList;
        this.movieHandler = movieHandler;
        
        setMainPanelMovieButtons(false);
        
        validator = new MovieValidator();
                
        showCurrentMovie(movies.get(index));
        
        this.setVisible(true);
        this.setTitle(Constants.EDIT_MOVIE_FRAME_TITLE);
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        moviePanel = new javax.swing.JPanel();
        movieCodeLabel = new javax.swing.JLabel();
        movieCodeField = new javax.swing.JTextField();
        movieTitleLabel = new javax.swing.JLabel();
        movieTitleField = new javax.swing.JTextField();
        movieYearLabel = new javax.swing.JLabel();
        movieYearField = new javax.swing.JTextField();
        moviePlotLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        moviePlotArea = new javax.swing.JTextArea();
        movieActorsLabel = new javax.swing.JLabel();
        movieActorFirstNameField = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        movieActorsList = new javax.swing.JList<>();
        movieDirector = new javax.swing.JLabel();
        movieDirectorFirstNameField = new javax.swing.JTextField();
        moviePlaytimeLabel = new javax.swing.JLabel();
        moviePlaytimeField = new javax.swing.JTextField();
        moviePriceLabel = new javax.swing.JLabel();
        moviePriceField = new javax.swing.JTextField();
        movieQuantityLabel = new javax.swing.JLabel();
        movieQuantityField = new javax.swing.JTextField();
        cancelButton = new javax.swing.JButton();
        editButton = new javax.swing.JButton();
        movieActorLastNameField = new javax.swing.JTextField();
        movieDirectorLastNameField = new javax.swing.JTextField();
        removeActorButton = new javax.swing.JButton();
        removeAllActorsButton = new javax.swing.JButton();
        movieTypeLabel = new javax.swing.JLabel();
        movieTypeComboBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        movieCodeLabel.setText("Code: ");

        movieTitleLabel.setText("Title:");

        movieYearLabel.setText("Year:");

        moviePlotLabel.setText("Plot:");

        moviePlotArea.setColumns(20);
        moviePlotArea.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        moviePlotArea.setRows(5);
        jScrollPane1.setViewportView(moviePlotArea);

        movieActorsLabel.setText("Actors:");

        movieActorsList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(movieActorsList);

        movieDirector.setText("Director: ");

        moviePlaytimeLabel.setText("Playtime (secs):");

        moviePriceLabel.setText("Price:");

        movieQuantityLabel.setText("Quantity:");

        cancelButton.setText("Cancel");

        editButton.setText("Edit");

        removeActorButton.setText("Remove actor");

        removeAllActorsButton.setText("Remove all");

        movieTypeLabel.setText("Type:");

        javax.swing.GroupLayout moviePanelLayout = new javax.swing.GroupLayout(moviePanel);
        moviePanel.setLayout(moviePanelLayout);
        moviePanelLayout.setHorizontalGroup(
            moviePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(moviePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(moviePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(moviePanelLayout.createSequentialGroup()
                        .addGroup(moviePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(moviePlotLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(movieTitleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(movieCodeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(moviePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(moviePanelLayout.createSequentialGroup()
                                .addGroup(moviePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(movieCodeField)
                                    .addComponent(movieTitleField, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addComponent(movieTypeLabel)
                                .addGap(18, 18, 18)
                                .addComponent(movieTypeComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(movieYearLabel)
                                .addGap(18, 18, 18)
                                .addComponent(movieYearField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(moviePanelLayout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(moviePanelLayout.createSequentialGroup()
                        .addGroup(moviePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, moviePanelLayout.createSequentialGroup()
                                .addComponent(moviePlaytimeLabel)
                                .addGap(18, 18, 18)
                                .addComponent(moviePlaytimeField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(moviePriceLabel)
                                .addGap(18, 18, 18)
                                .addComponent(moviePriceField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(movieQuantityLabel)
                                .addGap(18, 18, 18)
                                .addComponent(movieQuantityField))
                            .addGroup(moviePanelLayout.createSequentialGroup()
                                .addComponent(movieDirector)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(movieDirectorFirstNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(movieDirectorLastNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, moviePanelLayout.createSequentialGroup()
                                .addComponent(movieActorsLabel)
                                .addGap(18, 18, 18)
                                .addGroup(moviePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(moviePanelLayout.createSequentialGroup()
                                        .addComponent(movieActorFirstNameField)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(movieActorLastNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(moviePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(removeActorButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(removeAllActorsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, moviePanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(editButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelButton)))
                .addContainerGap())
        );
        moviePanelLayout.setVerticalGroup(
            moviePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(moviePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(moviePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(movieCodeLabel)
                    .addComponent(movieCodeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(moviePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(movieTitleLabel)
                    .addComponent(movieTitleField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(movieYearLabel)
                    .addComponent(movieYearField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(movieTypeLabel)
                    .addComponent(movieTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(moviePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(moviePlotLabel)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(moviePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(movieActorsLabel)
                    .addComponent(movieActorFirstNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(movieActorLastNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(moviePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(moviePanelLayout.createSequentialGroup()
                        .addComponent(removeActorButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(removeAllActorsButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(moviePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(movieDirector)
                    .addComponent(movieDirectorFirstNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(movieDirectorLastNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(moviePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(moviePlaytimeLabel)
                    .addComponent(moviePlaytimeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(moviePriceLabel)
                    .addComponent(moviePriceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(movieQuantityLabel)
                    .addComponent(movieQuantityField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(moviePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton)
                    .addComponent(editButton))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(moviePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(moviePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditMovieFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditMovieFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditMovieFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditMovieFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new EditMovieFrame().setVisible(true);
//            }
//        });
    }   
    private void initComboBox(){
        movieTypeComboBox.addItem(Constants.ACTION);
        movieTypeComboBox.addItem(Constants.ADVENTURE);
        movieTypeComboBox.addItem(Constants.COMEDY);
        movieTypeComboBox.addItem(Constants.CRIME);
        movieTypeComboBox.addItem(Constants.DRAMA);
        movieTypeComboBox.addItem(Constants.FANTASY);
        movieTypeComboBox.addItem(Constants.HISTORICAL);
        movieTypeComboBox.addItem(Constants.HORROR);
        movieTypeComboBox.addItem(Constants.MAGICAL);
        movieTypeComboBox.addItem(Constants.MYSTERY);
        movieTypeComboBox.addItem(Constants.PARANOID);
        movieTypeComboBox.addItem(Constants.PHILOSOPHICAL);
        movieTypeComboBox.addItem(Constants.POLITICAL);
        movieTypeComboBox.addItem(Constants.ROMANCE);
        movieTypeComboBox.addItem(Constants.SAGA);
        movieTypeComboBox.addItem(Constants.SATIRE);
        movieTypeComboBox.addItem(Constants.SCIENCE);
        movieTypeComboBox.addItem(Constants.SOCIAL);
        movieTypeComboBox.addItem(Constants.SPECULATIVE);
        movieTypeComboBox.addItem(Constants.THRILLER);
        movieTypeComboBox.addItem(Constants.URBAN);
        movieTypeComboBox.addItem(Constants.WESTERN);
    }
    
    private void bindListenerToButtons(){
        editButton.addActionListener(new ButtonListener());
        cancelButton.addActionListener(new ButtonListener());
    }
    
    private void setMainPanelMovieButtons(boolean enabled){
        for(JButton button : buttonList){
            button.setEnabled(enabled);
        }
    }
    
    private void showCurrentMovie(Movie movie){
        movieCodeField.setText(movie.getCode());
        movieTitleField.setText(movie.getTitle());
        movieTypeComboBox.setSelectedItem(movie.getType());
        movieYearField.setText(String.valueOf(movie.getYear()));
        moviePlotArea.setText(movie.getPlot());
        
        listModel = new DefaultListModel();
        for(MovieFactor actor : movie.getActors()){
            listModel.addElement(actor);
        }
        movieActorsList.setModel(listModel);
        movieDirectorFirstNameField.setText(movie.getDirector().getFirstName());
        movieDirectorLastNameField.setText(movie.getDirector().getLastName());
        moviePlaytimeField.setText(String.valueOf(movie.getPlayTime()));
        moviePriceField.setText(String.valueOf(movie.getPrice()));
        movieQuantityField.setText(String.valueOf(movie.getQuantity()));
    }
    
    private Movie getEditedMovie(){
        String code = movieCodeField.getText();
        String title = movieTitleField.getText();
        String type = (String)movieTypeComboBox.getSelectedItem();
        int year = Integer.parseInt(movieYearField.getText());
        String plot = moviePlotArea.getText();
        ArrayList<MovieFactor> actors = new ArrayList<MovieFactor>();
        for(int i=0; i<listModel.size(); i++){
            actors.add((MovieFactor)listModel.get(i));
        }
        String directorFirstName = movieDirectorFirstNameField.getText();
        String directorLastName = movieDirectorLastNameField.getText();
        MovieFactor director = new MovieFactor(directorFirstName, directorLastName);
        int playtime = Integer.parseInt(moviePlaytimeField.getText());
        double price = Double.parseDouble(moviePriceField.getText());
        int quantity = Integer.parseInt(movieQuantityField.getText());
        
        Movie movie = new Movie(code,title,type,year,plot,actors,director,playtime,price,quantity);
        return movie;
    }
    
    private void updateRow(int index, MoviePanel.MovieTableModel movieTableModel, Movie movie){
        movieTableModel.setValueAt(movie.getCode(), index, 1);
        movieTableModel.setValueAt(movie.getTitle(), index, 2);
        movieTableModel.setValueAt(String.valueOf(movie.getPrice()), index, 3);
        movieTableModel.setValueAt(String.valueOf(movie.getQuantity()), index, 4);
    }

    @Override
    public void windowOpened(WindowEvent e) {}

    @Override
    public void windowClosing(WindowEvent e) {
        setMainPanelMovieButtons(true);
    }

    @Override
    public void windowClosed(WindowEvent e) {}

    @Override
    public void windowIconified(WindowEvent e) {}

    @Override
    public void windowDeiconified(WindowEvent e) {}

    @Override
    public void windowActivated(WindowEvent e) {}

    @Override
    public void windowDeactivated(WindowEvent e) {}
    
    class ButtonListener implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent event) {
           Object source = event.getSource();
           if(source == editButton){
               Movie movie = getEditedMovie();
               if(validator.isValidMovie(movie)){
                   movieHandler.updateRecord(movie);
                   movies.set(index, movie);
                   updateRow(index, movieTableModel, movie);
                   Status.showInfoMessage(Constants.MOVIE_TABLE_UPDATED);
               }
               else Status.showErrorMessage(Constants.INVALID_DATA);
           }
           if(source == cancelButton){
               setMainPanelMovieButtons(true);
               dispose();
           }
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton editButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField movieActorFirstNameField;
    private javax.swing.JTextField movieActorLastNameField;
    private javax.swing.JLabel movieActorsLabel;
    private javax.swing.JList<String> movieActorsList;
    private javax.swing.JTextField movieCodeField;
    private javax.swing.JLabel movieCodeLabel;
    private javax.swing.JLabel movieDirector;
    private javax.swing.JTextField movieDirectorFirstNameField;
    private javax.swing.JTextField movieDirectorLastNameField;
    private javax.swing.JPanel moviePanel;
    private javax.swing.JTextField moviePlaytimeField;
    private javax.swing.JLabel moviePlaytimeLabel;
    private javax.swing.JTextArea moviePlotArea;
    private javax.swing.JLabel moviePlotLabel;
    private javax.swing.JTextField moviePriceField;
    private javax.swing.JLabel moviePriceLabel;
    private javax.swing.JTextField movieQuantityField;
    private javax.swing.JLabel movieQuantityLabel;
    private javax.swing.JTextField movieTitleField;
    private javax.swing.JLabel movieTitleLabel;
    private javax.swing.JComboBox<String> movieTypeComboBox;
    private javax.swing.JLabel movieTypeLabel;
    private javax.swing.JTextField movieYearField;
    private javax.swing.JLabel movieYearLabel;
    private javax.swing.JButton removeActorButton;
    private javax.swing.JButton removeAllActorsButton;
    // End of variables declaration//GEN-END:variables
}
